name: Lint
on: [push]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Lint
        run: pylint main.py
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Tests
        run: python3 test.py
  build:
    runs-on: self-hosted
    steps:
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build Docker image
        run: docker build -t figures .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 figures