name: Lint
on: [push]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Lint
        run: pylint main.py
  test:
    needs: [ lint ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Tests
        run: python test.py
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: false
          tags: user/app:latest