name: Tests
on: [push]
jobs:
  test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirments.txt
      - name: Tests
        run: python test.py